/**
 * IMAGERY MANIFEST
 * ================
 *
 * Every image slot on this site is declared here, whether or not a real asset
 * exists for it yet. The manifest is the answer to "what imagery does this site
 * still owe?" and it is the thing `npm run placeholder-audit` reads to decide
 * whether the site is shippable.
 *
 * Rules:
 *   - A slot with status "pending" has NO asset. Components must render the
 *     designed empty state for it, not a grey box, not a stock photo, and not
 *     an <img> pointing at a file that does not exist. A missing image is
 *     honest; a fake one is not.
 *   - A slot only moves to "ready" in the same commit that adds the real file
 *     under /public and fills in `src`, `width`, `height`, and `alt`.
 *   - Alt text is written here, next to the intent of the slot, so it is
 *     composed deliberately rather than typed into a component at 2am. It must
 *     never contain the founder's name.
 *
 * WHAT CHANGED, AND WHY THE REMAINING PENDING SLOTS ARE NOT A BACKLOG
 * -------------------------------------------------------------------
 * The three slots that could be produced honestly have been. The Open Graph
 * card and the app icon are generated from the Craftline wordmark by
 * `npm run brand-assets`, and the Wattsmith card carries that brand's real
 * delivered lockup rather than a photograph of it.
 *
 * The three still pending all want photographs of people doing work. Craftline
 * has no such photographs of its own operations, and buying stock ones is
 * refused rather than deferred: a franchisor in formation showing crews, trucks,
 * and job sites that are not its own implies scale that does not exist, which
 * belongs in the same category as inventing a franchisee count. So the pages
 * that would have used them carry abstract geometry from the design system
 * instead, and they are built to look finished without a photograph. These slots
 * stay tracked because the direction is worth keeping, not because the site is
 * waiting on them.
 *
 * NOT TRACKED HERE, DELIBERATELY: the inline SVG in src/components/graphic.tsx
 * and the brand lockups in src/components/brand/. Those are components, not
 * assets. They ship inside the HTML, have no file under /public, and cannot be
 * a broken image or a placeholder, which is the entire failure mode this
 * manifest exists to catch. The one exception is the Wattsmith lockup, whose
 * source file IS committed and so IS tracked below.
 */

export type ImageStatus = "pending" | "ready";

export interface ImageSlot {
  /** Stable key. Referenced by components and by the audit script. */
  id: string;
  /** Where it appears, in plain language. */
  location: string;
  /** What the finished asset needs to show. Direction for whoever makes it. */
  intent: string;
  /** Target intrinsic dimensions. Aspect ratio is the binding part. */
  aspect: string;
  status: ImageStatus;
  /** Path under /public. Null while pending. */
  src: string | null;
  /**
   * Intrinsic pixel dimensions of the real asset. Null while pending, and null
   * for vector assets that have no single intrinsic size. Open Graph consumers
   * want these declared, so they are recorded rather than measured at runtime.
   */
  width: number | null;
  height: number | null;
  /**
   * Alt text for the finished asset. Null for slots that are decorative when
   * they land, in which case the component renders them hidden from assistive
   * technology rather than with an empty alt on a meaningful image.
   */
  alt: string | null;
}

export const IMAGE_SLOTS: ImageSlot[] = [
  {
    id: "og-default",
    location: "Open Graph and Twitter card fallback for every page.",
    intent:
      "The Craftline wordmark set in type on a charcoal field, with generous margin. No photograph, no emblem, no tagline. Produced from the identity system rather than shot, and to be replaced the day a real identity exists. Generated by scripts/brand-assets.mjs from the same Archivo tracked caps treatment the site header uses, so a shared link and the page it opens carry the same mark.",
    aspect: "1200x630",
    status: "ready",
    src: "/brand/craftline-og-default.png",
    width: 1200,
    height: 630,
    alt: "The Craftline Brands wordmark on a charcoal field.",
  },
  {
    id: "app-icon",
    location: "Browser tab, bookmark, and home screen icon.",
    intent:
      "A single letterform drawn from the wordmark on a charcoal field: the C, with the bronze rule reduced to a bar along the foot of the tile. Still not a commissioned emblem, which was the original objection and remains correct. It is the wordmark cut down to what survives at 16 pixels, so it carries no recognition the real identity would have to fight. Generated by scripts/brand-assets.mjs at each size rather than downscaled, so the bar stays crisp.",
    aspect: "512x512",
    status: "ready",
    src: "/brand/craftline-icon-512.png",
    width: 512,
    height: 512,
    alt: null,
  },
  {
    id: "brand-card-wattsmith",
    location:
      "Wattsmith Electric card on the home page, the brands index, and the brand showcase.",
    intent:
      "The delivered Wattsmith Electric lockup, copied from that brand's own repository so the two properties cannot drift apart. This file is the designer master and the source of truth; it is rendered as inline SVG by src/components/brand/wattsmith-lockup.tsx so the navy artwork can reverse on a navy field, which an <img> cannot do. Decorative at every call site, because the brand name is always present as visible text beside it.",
    aspect: "1372x498",
    status: "ready",
    src: "/brand/wattsmith-electric-lockup.svg",
    width: null,
    height: null,
    alt: null,
  },
  {
    id: "home-hero",
    location: "Home page hero, behind the headline.",
    intent:
      "Wide environmental shot of skilled trade work in progress, shot dark and low contrast so headline type stays legible over it. Real technicians on a real job, from a Craftline brand, never stock. No posed models, no crossed arms, no branded truck hero shot. The hero now carries the abstract rule field from src/components/graphic.tsx and looks deliberate without a photograph, so the bar for replacing it has gone up rather than down: this only lands if the photograph is genuinely better than the geometry.",
    aspect: "16x9",
    status: "pending",
    src: null,
    width: null,
    height: null,
    alt: null,
  },
  {
    id: "about-operations",
    location: "About page, alongside the holding company explanation.",
    intent:
      "Documentation, training, or dispatch in use. The point is the system behind the trade, not the trade itself. Must be our own material, not stock office imagery.",
    aspect: "4x3",
    status: "pending",
    src: null,
    width: null,
    height: null,
    alt: "Craftline operating procedures in use.",
  },
  {
    id: "franchising-operator",
    location: "Franchising page, supporting the operator profile section.",
    intent:
      "An owner operator running the business side of a trade company. Must not read as a sales pitch and must not imply any financial outcome. A stock photograph of a smiling person in a branded polo is the exact thing this slot exists to refuse.",
    aspect: "3x2",
    status: "pending",
    src: null,
    width: null,
    height: null,
    alt: "An owner operator at work.",
  },
];

/** Slots still awaiting a real asset. Used by the placeholder audit. */
export const PENDING_IMAGE_SLOTS = IMAGE_SLOTS.filter(
  (slot) => slot.status === "pending",
);

/**
 * Lookup by id. Throws on an unknown key rather than returning undefined: a
 * typo in a slot id should fail the build, not silently render nothing.
 */
export function getImageSlot(id: string): ImageSlot {
  const slot = IMAGE_SLOTS.find((candidate) => candidate.id === id);
  if (!slot) {
    throw new Error(
      `Unknown image slot "${id}". Every image on this site must be declared in src/data/images.ts.`,
    );
  }
  return slot;
}

/**
 * A slot that is ready, with its asset path guaranteed present.
 *
 * Metadata builders need `src`, `width`, `height`, and `alt` as non null values.
 * Rather than have every caller assert that a slot it knows is ready really is,
 * this narrows once and throws loudly if a slot is downgraded to pending
 * without its consumers being updated in the same commit.
 */
export function getReadyImage(id: string): {
  src: string;
  width: number;
  height: number;
  alt: string;
} {
  const slot = getImageSlot(id);
  if (
    slot.status !== "ready" ||
    !slot.src ||
    slot.width === null ||
    slot.height === null ||
    !slot.alt
  ) {
    throw new Error(
      `Image slot "${id}" is consumed somewhere that requires a ready asset ` +
        "with dimensions and alt text, but it is not fully populated. Either " +
        "restore the asset or remove the consumer.",
    );
  }
  return {
    src: slot.src,
    width: slot.width,
    height: slot.height,
    alt: slot.alt,
  };
}
